# 将静态内容部署到 GitHub Pages 的简易工作流程
name: Deploy static content to Pages

on:
  # 仅在推送到默认分支时运行。
  push:
    branches: ['master']

  # 这个选项可以使你手动在 Action tab 页面触发工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages。
permissions:
  contents: write
  pages: write
  id-token: write

# 允许一个并发的部署
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # 单次部署的工作描述
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04  # 当前稳定版 LTS runs-on: ubuntu-24.04-2024.04.1
    steps:
      - name: Restore pnpm cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
      - name: pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.19
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install requests package
        run: pnpm install
      - name: Build
        run: pnpm run build

      # 新增的CHANGELOG生成步骤
      # - name: Install Ruby and github_changelog_generator
      #   run: |
      #     sudo apt-get install ruby-full
      #     sudo gem install github_changelog_generator
      #     github_changelog_generator \
      #       --user willysliang \
      #       --project core \
      #       --token ${{ secrets.GITHUB_TOKEN }} \
      #       --future-release v2.0.0 \
      #       --header-label "# Changelog" \
      #       --configure-sections '{"enhancements":{"prefix":"* **Enhancements:**","labels":["enhancement", "feature"]},"bugs":{"prefix":"* **Fixed bugs:**","labels":["bug"]}}' \
      #       --add-sections '{"deprecated":{"prefix":"* **Deprecated:**","labels":["deprecated"]}}'
      # - name: Commit CHANGELOG
      #   run: |
      #     git fetch --unshallow || git fetch
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add CHANGELOG.md
      #     git commit -m "docs: update CHANGELOG" || echo "No changes to commit"
      #     git push origin HEAD:master --force
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4  # 显式使用最新版
        with:
          name: build-output
          path: |
            dist/
            *.log
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3